[client] Define the type for require.ensure. Fixes the following tsc error:
client/init.js:8:13 - error TS2339: Property 'ensure' does not exist on type 'NodeRequire'.

8     require.ensure(['whatwg-fetch'], require => {

The `require` we use here is the require provided by webpack. This type definition allows not to install a type definition.